In [94]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn import datasets

In [95]:
base = datasets.load_iris()
base

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [96]:
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [97]:
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [98]:
classe_dumy = to_categorical(classe)
classe_dumy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [99]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores,
                                                 classe_dumy,
                                                 test_size = 0.3,
                                                 random_state = 0)

In [100]:
modelo = Sequential()

modelo.add(Dense(units = 5, input_dim = 4))

modelo.add(Dense(units = 4))

modelo.add(Dense(units=3, activation="softmax"))

In [101]:
modelo.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [110]:
modelo.compile(optimizer = "adam", loss = "categorical_crossentropy",
              metrics = ["accuracy"])

modelo.fit(x_treino, y_treino, epochs = 100,
          validation_data = (x_teste, y_teste))

#    ACCURACY MALHORA SE VOCE COLOCAR MAIS EPOCHS
#    COLOQUEI APENAS 100 PARA FINS DIDATICOS PARA NAO FICAR POLUIDO

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.3434 - loss: 1.7159 - val_accuracy: 0.2444 - val_loss: 1.9295
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3548 - loss: 1.5682 - val_accuracy: 0.2444 - val_loss: 1.8186
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3809 - loss: 1.4573 - val_accuracy: 0.2444 - val_loss: 1.7174
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3746 - loss: 1.3702 - val_accuracy: 0.2444 - val_loss: 1.6284
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3850 - loss: 1.2902 - val_accuracy: 0.2444 - val_loss: 1.5464
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3840 - loss: 1.2460 - val_accuracy: 0.2444 - val_loss: 1.4719
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4007 - loss: 1.1624 - val_accuracy: 0.2444 - val_loss: 1.4076
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3392 - loss: 1.2092 - val_accuracy: 0.2444 - val_loss:

In [112]:
previsoes = modelo.predict(x_teste)
previsoes

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step 


array([[0.01733603, 0.31295756, 0.66970634],
       [0.05862534, 0.4356569 , 0.5057178 ],
       [0.95668226, 0.03970709, 0.00361066],
       [0.00472091, 0.22479549, 0.7704836 ],
       [0.8894942 , 0.0961451 , 0.01436062],
       [0.00955551, 0.24940875, 0.74103576],
       [0.9143344 , 0.0761423 , 0.00952331],
       [0.06363977, 0.4340253 , 0.502335  ],
       [0.03917291, 0.4057564 , 0.5550707 ],
       [0.11041114, 0.46802714, 0.4215617 ],
       [0.00996794, 0.24724372, 0.7427883 ],
       [0.0929563 , 0.44714123, 0.45990252],
       [0.04946434, 0.38534948, 0.5651862 ],
       [0.04887175, 0.41911578, 0.53201246],
       [0.05197765, 0.39222282, 0.55579954],
       [0.9232887 , 0.0678383 , 0.00887295],
       [0.06425463, 0.41380477, 0.52194065],
       [0.05637663, 0.3836558 , 0.5599675 ],
       [0.8425748 , 0.13443105, 0.02299413],
       [0.94038355, 0.05428303, 0.00533335],
       [0.02722535, 0.3335357 , 0.63923895],
       [0.07416031, 0.39965007, 0.52618957],
       [0.

In [114]:
#CONVEÇAO PARA TRUE E FALSE MELHOR ENTENDIMENTO

previsoes = (previsoes > 0.05)
previsoes

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False,  True,  True],
       [ True,  True, False],
       [False,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True, False],
       [False,  True,  True],
       [ True, False, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [Fa

In [116]:
y_teste_matrix = [np.argmax(t) for t in y_teste]
Y_previsoes_matrix = [np.argmax(t) for t in previsoes]

In [120]:
confusao = confusion_matrix(y_teste_matrix, Y_previsoes_matrix)
confusao

array([[16,  0,  0],
       [14,  4,  0],
       [ 0, 11,  0]], dtype=int64)